version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: slews-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports: 
      - "9002:9000"
    networks:
      - slews-app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: slews-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - slews-app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: slews-db
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: kradworkz
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - slews-app-network

#Docker Networks
networks:
  slews-app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local

